### ISSUE TITLE
Plot error on Python3.6.9: [GCC 8.4.0] on Linux

### ISSUE THREAD

**Issue by clubfor5** [location-competition/indoor-location-competition-20#4]
Traceback (most recent call last):
  File "main.py", line 204, in <module>
    fig = visualize_trajectory(step_positions, floor_plan_filename, width_meter, height_meter, mode='markers', title='Step Position', show=True)
  File "/home/zz/indoor-location-competition-20/visualize_f.py", line 41, in visualize_trajectory
    name='trajectory',
  File "/usr/lib/python3/dist-packages/plotly/graph_objs/graph_objs.py", line 377, in __init__
    self.__setitem__(key, val, _raise=_raise)
  File "/usr/lib/python3/dist-packages/plotly/graph_objs/graph_objs.py", line 432, in __setitem__
    value = self._value_to_graph_object(key, value, _raise=_raise)
  File "/usr/lib/python3/dist-packages/plotly/graph_objs/graph_objs.py", line 543, in _value_to_graph_object
    _parent=self, _parent_key=key)
  File "/usr/lib/python3/dist-packages/plotly/graph_objs/graph_objs.py", line 799, in create
    return PlotlyDict(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/plotly/graph_objs/graph_objs.py", line 377, in __init__
    self.__setitem__(key, val, _raise=_raise)
  File "/usr/lib/python3/dist-packages/plotly/graph_objs/graph_objs.py", line 428, in __setitem__
    raise exceptions.PlotlyDictKeyError(self, path)
plotly.exceptions.PlotlyDictKeyError: 'shape' is not allowed in 'line'

Path To Error: ['line']['shape']

Valid attributes for 'line' at path ['line'] under parents ['scattergl']:

    ['autocolorscale', 'cauto', 'cmax', 'cmin', 'color', 'colorscale',
    'colorsrc', 'dash', 'reversescale', 'width', 'widthsrc']

Run `<line-object>.help('attribute')` on any of the above.
'<line-object>' is the object at ['line']

**Comment by clubfor5** [comment]
Solved... Update the latest plotly lib with pip install plotly==4.9.0
